### ISSUE TITLE
Double check if per-second rate is accurate.

### ISSUE THREAD

**Issue by mgulimonov** [alvaromontoro/bezos-calculator#4]
Sorry for nitpicking, but I don't see how $56B is translated to 311M/per day.

56B / 365 days ~ 153M
56B / 261 working days ~ 214M

Am I missing something?

**Comment by alvaromontoro** [comment]
The explanation is in the [BuzzFeed article](https://www.buzzfeed.com/mjs538/jeff-bezos-wealth). **The numbers are not for the whole 2020, but only for half a year** (between January 1st and July 1st, or 182 days).

   56.7B in 6 months.
~ 9.45B per month
~ 311M per day
~ 12M per hour
~ 216,000 per minute
~ 3,605 per second

Their explanation is a bit fuzzy, but the numbers end up matching up if we take into account the 182 days instead of the 6 months:

   56.7B in 182 days
~ 311.53M per day (56.7 / 182)
~ 12.98M per hour (311.53 / 24)
~ 216,346.61 per minute (12.98 / 60)
~ 3,605.76 per second (216,346 / 60)

**Comment by alvaromontoro** [comment]
I will update the README to indicate that the amount is only for the first six months of 2020.
